// packages/svelte/src/components/FileInput/Trigger.svelte
<script lang="ts">
  import { useFileInputContext } from './context.js'

  import type { Snippet } from 'svelte'
  import type { HTMLLabelAttributes } from 'svelte/elements'

  type Props = Omit<HTMLLabelAttributes, 'for'> & {
    ref?: HTMLLabelElement | null
    /** What the trigger reads. It is the accessible name of the file input. */
    children: Snippet
  }

  let { ref = $bindable(null), children, ...rest }: Props = $props()

  const fileInput = useFileInputContext()
</script>

<!-- A label rather than a button: the browser forwards the click to the
  input, the input stays the one thing in the tab order, and its name comes
  from this text. -->
<label
  bind:this={ref}
  for={fileInput.inputId}
  data-disabled={fileInput.disabled ? '' : undefined}
  {...rest}
>
  {@render children()}
</label>

// packages/react/src/components/FileInput/Trigger.tsx
import { ComponentPropsWithoutRef, forwardRef, ReactNode } from 'react'

import { useFileInputContext } from './context'

export interface FileInputTriggerProps {
  /** What the trigger reads. It is the accessible name of the file input. */
  children: ReactNode
}

type Props = FileInputTriggerProps &
  Omit<
    ComponentPropsWithoutRef<'label'>,
    keyof FileInputTriggerProps | 'htmlFor'
  >

/**
 * Opens the file picker, and names the input for a screen reader.
 *
 * A `<label>` rather than a `<button>`: the browser forwards the click to the
 * input on its own, the input stays the one thing in the tab order, and its
 * accessible name comes from this text without an `aria-label` to keep in
 * step. A disabled input ignores the click, so nothing has to be intercepted.
 */
export const Trigger = /* @__PURE__ */ forwardRef<HTMLLabelElement, Props>(
  ({ children, ...props }, ref) => {
    const { inputId, disabled } = useFileInputContext()

    return (
      <label
        ref={ref}
        htmlFor={inputId}
        data-disabled={disabled ? '' : undefined}
        {...props}
      >
        {children}
      </label>
    )
  },
)
