// site/examples/svelte/AnimationCanvas.svelte
<script lang="ts">
  import { AnimationCanvas } from '@tremolo-ui/svelte'
</script>

<AnimationCanvas
  width={200}
  height={200}
  init={(ctx) => {
    ctx.font = '16px sans-serif'
  }}
  draw={(ctx, { width, height, count }) => {
    ctx.clearRect(0, 0, width, height)
    ctx.fillText(`frame: ${count}`, 0, 16)
    // draw sine wave
    const halfH = height / 2
    ctx.strokeStyle = '#29bbf0'
    ctx.beginPath()
    for (let i = 0; i < width; i++) {
      const y =
        halfH + halfH * 0.5 * Math.sin((4 * Math.PI * (i + count * 2)) / width)
      if (i === 0) ctx.moveTo(i, y)
      else ctx.lineTo(i, y)
    }
    ctx.stroke()
  }}
/>

// site/examples/vue/AnimationCanvas.vue
<script setup lang="ts">
import { AnimationCanvas, type DrawFunction } from '@tremolo-ui/vue'

const draw: DrawFunction = (ctx, { width, height, count }) => {
  ctx.clearRect(0, 0, width, height)
  ctx.fillText(`frame: ${count}`, 0, 16)
  // draw sine wave
  const halfH = height / 2
  ctx.strokeStyle = '#29bbf0'
  ctx.beginPath()
  for (let i = 0; i < width; i++) {
    const y =
      halfH + halfH * 0.5 * Math.sin((4 * Math.PI * (i + count * 2)) / width)
    if (i === 0) ctx.moveTo(i, y)
    else ctx.lineTo(i, y)
  }
  ctx.stroke()
}
</script>

<template>
  <AnimationCanvas
    :width="200"
    :height="200"
    :init="(ctx) => (ctx.font = '16px sans-serif')"
    :draw="draw"
  />
</template>
