// site/examples/svelte/FileInput.svelte
<script lang="ts">
  import { FileInput } from '@tremolo-ui/svelte'

  // Copy this file from the Styling page into your own project.
  import fileInputTheme from './FileInput.module.css'

  let files: File[] = $state([])
  let rejected: File[] = $state([])
</script>

<FileInput.Root
  class={fileInputTheme.root}
  accept="audio/*"
  multiple
  onChange={(picked) => {
    rejected = []
    files = picked
  }}
  onReject={(picked) => (rejected = picked)}
>
  <FileInput.Trigger class={fileInputTheme.trigger}
    >Choose audio</FileInput.Trigger
  >
  <span>{files.length > 0 ? `${files.length} selected` : 'No file'}</span>
</FileInput.Root>
<ul>
  {#each files as file (file.name)}
    <li>{file.name} ({file.type || 'unknown type'})</li>
  {/each}
</ul>
{#if rejected.length > 0}
  <p>Not audio: {rejected.map((file) => file.name).join(', ')}</p>
{/if}

// site/examples/vue/FileInput.vue
<script setup lang="ts">
import { ref } from 'vue'

import { FileInput, FileInputTrigger } from '@tremolo-ui/vue'

// Copy this file from the Styling page into your own project.
import fileInputTheme from './FileInput.module.css'

const files = ref<File[]>([])
const rejected = ref<File[]>([])

function onChange(picked: File[]) {
  rejected.value = []
  files.value = picked
}
</script>

<template>
  <FileInput
    :class="fileInputTheme.root"
    accept="audio/*"
    multiple
    @change="onChange"
    @reject="(picked) => (rejected = picked)"
  >
    <FileInputTrigger :class="fileInputTheme.trigger">
      Choose audio
    </FileInputTrigger>
    <span>{{ files.length > 0 ? `${files.length} selected` : 'No file' }}</span>
  </FileInput>
  <ul>
    <li v-for="file in files" :key="file.name">
      {{ file.name }} ({{ file.type || 'unknown type' }})
    </li>
  </ul>
  <p v-if="rejected.length > 0">
    Not audio: {{ rejected.map((file) => file.name).join(', ') }}
  </p>
</template>
