// packages/react/src/components/Knob/ActiveLine.tsx
import { SVGProps } from 'react'

import { knobArcPath, knobArcRadius } from '@tremolo-ui/dom'

import { useCheckPlacement } from '../_util/Placement'

import { useKnobContext } from './context'

export function ActiveLine({
  stroke = 'currentColor',
  strokeWidth = 6,
  className,
  ...props
}: Omit<SVGProps<SVGPathElement>, 'd'>) {
  useCheckPlacement('Knob.ActiveLine', 'Knob.SVGRoot')

  const r2 = useKnobContext((s) => s.r2)
  const r3 = useKnobContext((s) => s.r3)

  const radius = knobArcRadius(strokeWidth)

  return (
    <path
      className={className}
      d={knobArcPath(r2, r3, radius)}
      fill="none"
      stroke={stroke}
      strokeWidth={strokeWidth}
      {...props}
    />
  )
}

// packages/svelte/src/components/Knob/ActiveLine.svelte
<script lang="ts">
  import { knobArcPath, knobArcRadius } from '@tremolo-ui/dom'

  import { checkPlacement } from '../_util/placement.js'

  import { useKnobContext } from './context.js'

  import type { SVGAttributes } from 'svelte/elements'

  type Props = Omit<SVGAttributes<SVGPathElement>, 'd'>

  let {
    stroke = 'currentColor',
    'stroke-width': strokeWidth = 6,
    ...rest
  }: Props = $props()

  checkPlacement('Knob.ActiveLine', 'Knob.SVGRoot')
  const knob = useKnobContext()
  const radius = $derived(knobArcRadius(strokeWidth ?? undefined))
</script>

<path
  d={knobArcPath(knob.angles.r2, knob.angles.r3, radius)}
  fill="none"
  {stroke}
  stroke-width={strokeWidth}
  {...rest}
/>
