// packages/react/src/components/Knob/InactiveLine.tsx
import { SVGProps } from 'react'

import { knobArcPath, knobArcRadius } from '@tremolo-ui/dom'

import { useCheckPlacement } from '../_util/Placement'

import { useKnobContext } from './context'

export function InactiveLine({
  stroke = 'currentColor',
  strokeWidth = 6,
  className,
  ...props
}: Omit<SVGProps<SVGPathElement>, 'd'>) {
  useCheckPlacement('Knob.InactiveLine', 'Knob.SVGRoot')

  const min = useKnobContext((s) => s.min)
  const max = useKnobContext((s) => s.max)
  const startValue = useKnobContext((s) => s.startValue)

  const r1 = useKnobContext((s) => s.r1)
  const r2 = useKnobContext((s) => s.r2)
  const r3 = useKnobContext((s) => s.r3)
  const r4 = useKnobContext((s) => s.r4)

  const radius = knobArcRadius(strokeWidth)

  return (
    <>
      {startValue > min && (
        <path
          className={className}
          d={knobArcPath(r1, r2, radius)}
          fill="none"
          stroke={stroke}
          strokeWidth={strokeWidth}
          {...props}
        />
      )}
      {startValue < max && (
        <path
          className={className}
          d={knobArcPath(r3, r4, radius)}
          fill="none"
          stroke={stroke}
          strokeWidth={strokeWidth}
          {...props}
        />
      )}
    </>
  )
}

// packages/svelte/src/components/Knob/InactiveLine.svelte
<script lang="ts">
  import { knobArcPath, knobArcRadius } from '@tremolo-ui/dom'

  import { checkPlacement } from '../_util/placement.js'

  import { useKnobContext } from './context.js'

  import type { SVGAttributes } from 'svelte/elements'

  type Props = Omit<SVGAttributes<SVGPathElement>, 'd'>

  let { stroke = 'currentColor', 'stroke-width': strokeWidth = 6, ...rest }: Props =
    $props()

  checkPlacement('Knob.InactiveLine', 'Knob.SVGRoot')
  const knob = useKnobContext()
  const radius = $derived(knobArcRadius(strokeWidth ?? undefined))
</script>

<!-- The travel on either side of the active arc. -->
{#if knob.startValue > knob.min}
  <path
    d={knobArcPath(knob.angles.r1, knob.angles.r2, radius)}
    fill="none"
    {stroke}
    stroke-width={strokeWidth}
    {...rest}
  />
{/if}
{#if knob.startValue < knob.max}
  <path
    d={knobArcPath(knob.angles.r3, knob.angles.r4, radius)}
    fill="none"
    {stroke}
    stroke-width={strokeWidth}
    {...rest}
  />
{/if}
