// packages/react/src/components/Knob/Thumb.tsx
import { SVGProps } from 'react'

import { clamp } from '@tremolo-ui/functions'

import { cx } from '../_util/cx'
import { useCheckPlacement } from '../_util/placement'

import { useKnobContext, viewBoxSize } from './context'

interface Props {
  /** color */
  thumb?: string
  /** color */
  thumbLine?: string
  /** percent (0-100) */
  thumbSize?: number
  /** percent (0-100) */
  thumbLineWeight?: number
  /** percent (0-100) */
  thumbLineLength?: number

  classes?: {
    thumb?: string
    thumbLine?: string
  }
}

export function Thumb({
  className,

  thumb = 'currentColor',
  thumbLine = 'currentColor',
  thumbSize = 84,
  thumbLineWeight = 6,
  thumbLineLength = 35,
  classes,

  ...props
}: Props & Omit<SVGProps<SVGSVGElement>, 'd' | keyof Props>) {
  useCheckPlacement('Knob.Thumb', 'Knob.SVGRoot')

  const angleRange = useKnobContext((s) => s.angleRange)

  const p = useKnobContext((s) => s.p)
  const r1 = useKnobContext((s) => s.r1)

  return (
    <svg className={cx('tremolo-knob-thumb', classes?.thumb)} {...props}>
      <circle cx="50%" cy="50%" r={`${thumbSize / 2}%`} fill={thumb} />
      <line
        className={cx('tremolo-knob-thumb-line', classes?.thumbLine)}
        x1="50%"
        y1={`${(viewBoxSize - clamp(thumbSize, 0, 100)) / 2}%`}
        x2="50%"
        y2={`${thumbLineLength}%`}
        stroke={thumbLine}
        strokeWidth={`${thumbLineWeight}%`}
        // NOTE
        // https://bugs.webkit.org/show_bug.cgi?id=201854
        // https://developer.mozilla.org/en-US/docs/Web/SVG/Reference/Attribute/transform-origin#browser_compatibility
        style={{
          transform: `rotate(${r1 + p * angleRange}deg)`,
          transformOrigin: '50% 50%',
        }}
      />
    </svg>
  )
}

// packages/svelte/src/components/Knob/Thumb.svelte
<script lang="ts">
  import { KNOB_VIEWBOX_SIZE } from '@tremolo-ui/dom'
  import { clamp } from '@tremolo-ui/functions'

  import { checkPlacement } from '../_util/placement.js'

  import { useKnobContext } from './context.js'
  import type { KnobThumbProps } from './types.js'

  import type { SVGAttributes } from 'svelte/elements'

  type Props = KnobThumbProps &
    Omit<SVGAttributes<SVGSVGElement>, keyof KnobThumbProps>

  let {
    thumb = 'currentColor',
    thumbLine = 'currentColor',
    thumbSize = 84,
    thumbLineWeight = 6,
    thumbLineLength = 35,
    classes,
    ...rest
  }: Props = $props()

  checkPlacement('Knob.Thumb', 'Knob.SVGRoot')
  const knob = useKnobContext()
  const angle = $derived(knob.angles.r1 + knob.angles.p * knob.angleRange)
</script>

<svg {...rest}>
  <circle cx="50%" cy="50%" r="{thumbSize / 2}%" fill={thumb} />
  <line
    class={classes?.thumbLine}
    x1="50%"
    y1="{(KNOB_VIEWBOX_SIZE - clamp(thumbSize, 0, 100)) / 2}%"
    x2="50%"
    y2="{thumbLineLength}%"
    stroke={thumbLine}
    stroke-width="{thumbLineWeight}%"
    style:transform="rotate({angle}deg)"
    style:transform-origin="50% 50%"
  />
</svg>
