// packages/react/src/components/XYPad/Thumb.tsx
import {
  AriaAttributes,
  ComponentPropsWithoutRef,
  CSSProperties,
  forwardRef,
  ReactNode,
  useImperativeHandle,
  useRef,
} from 'react'

import { useCheckPlacement } from '../_util/Placement'
import { VisuallyHiddenRangeInput } from '../_util/VisuallyHiddenRangeInput'

import { toXY, useXYPadContext, type XYInput } from './context'

export interface XYPadThumbProps {
  /**
   * Size comes from the `--thumb-size` CSS variable on `XYPad.Root`, so that
   * the root can reserve the matching amount of space around the area.
   */
  color?: string

  className?: string
  style?: CSSProperties
  /**
   * Rendered inside the thumb. The thumb is one element either way, so what
   * is passed here is decoration on top of it rather than a replacement for
   * it — `className` and `style` are how its own appearance is changed.
   */
  children?: ReactNode

  /**
   * The accessible name of each axis. There are two range inputs inside the
   * thumb, so this takes one name per axis; a single string names them both,
   * which is rarely what you want.
   */
  'aria-label'?: XYInput<AriaAttributes['aria-label']>
  'aria-labelledby'?: XYInput<AriaAttributes['aria-labelledby']>
  'aria-describedby'?: XYInput<AriaAttributes['aria-describedby']>
  /** What the value of each axis means, when the number does not say it. */
  'aria-valuetext'?: XYInput<AriaAttributes['aria-valuetext']>
}

export interface XYPadThumbMethods {
  focus: () => void
  blur: () => void
}

type Props = XYPadThumbProps &
  Omit<ComponentPropsWithoutRef<'div'>, keyof XYPadThumbProps>

export const Thumb = /* @__PURE__ */ forwardRef<XYPadThumbMethods, Props>(
  function Thumb(
    {
      color,
      children,
      className,
      style,
      'aria-label': ariaLabel,
      'aria-labelledby': ariaLabelledby,
      'aria-describedby': ariaDescribedby,
      'aria-valuetext': ariaValuetext,
      ...props
    },
    forwardedRef,
  ) {
    const xInputRef = useRef<HTMLInputElement>(null)
    const yInputRef = useRef<HTMLInputElement>(null)
    const {
      value,
      min,
      max,
      step,
      disabled,
      readonly,
      onChange,
      percent,
      thumbRef,
    } = useXYPadContext()

    // The thumb is positioned against the area.
    useCheckPlacement('XYPad.Thumb', 'XYPad.Area')

    // Per axis, since the thumb holds one input for each.
    const labels = toXY(ariaLabel)
    const labelledby = toXY(ariaLabelledby)
    const describedby = toXY(ariaDescribedby)
    const valueText = toXY(ariaValuetext)

    const methods = () => ({
      focus() {
        if (!disabled) xInputRef.current?.focus()
      },
      blur() {
        xInputRef.current?.blur()
        yInputRef.current?.blur()
      },
    })

    useImperativeHandle(forwardedRef, methods, [disabled])
    // Root focuses the thumb when a drag starts, wherever the user placed it.
    useImperativeHandle(thumbRef, methods, [disabled])

    return (
      <div
        className={className}
        data-disabled={disabled || undefined}
        data-readonly={readonly || undefined}
        {...props}
        style={{
          ...{ '--color': color },
          // Not a style but the mechanics of the position below: the thumb is
          // placed by a percentage of the area, which needs it out of flow and
          // measured from its own centre.
          position: 'absolute',
          translate: 'var(--translate, -50% -50%)',
          zIndex: 100,
          ...style,
          // Where the thumb sits is the component's decision, not a style: a
          // `left` from the caller would take it off the area, so it is written
          // after theirs.
          left: `${percent[0]}%`,
          top: `${percent[1]}%`,
        }}
      >
        {([0, 1] as const).map((axis) => (
          <VisuallyHiddenRangeInput
            key={axis}
            ref={axis === 0 ? xInputRef : yInputRef}
            data-axis={axis === 0 ? 'x' : 'y'}
            value={value[axis]}
            min={min[axis]}
            max={max[axis]}
            step={step[axis]}
            disabled={disabled}
            aria-readonly={readonly}
            aria-orientation={axis === 0 ? 'horizontal' : 'vertical'}
            aria-label={labels[axis] ?? (axis === 0 ? 'x' : 'y')}
            aria-labelledby={labelledby[axis]}
            aria-describedby={describedby[axis]}
            aria-valuetext={valueText[axis]}
            onChange={(event) => {
              if (readonly) {
                event.currentTarget.value = String(value[axis])
                return
              }
              const next = [...value] as [number, number]
              next[axis] = event.currentTarget.valueAsNumber
              onChange?.(next)
            }}
          />
        ))}
        {children}
      </div>
    )
  },
)

// packages/svelte/src/components/XYPad/Thumb.svelte
<script lang="ts">
  import { toXY } from '@tremolo-ui/dom'

  import { checkPlacement } from '../_util/placement.js'
  import VisuallyHiddenRangeInput from '../_util/VisuallyHiddenRangeInput.svelte'

  import { useXYPadContext } from './context.js'
  import type { XYPadThumbProps } from './types.js'

  import type { HTMLAttributes } from 'svelte/elements'

  type Props = XYPadThumbProps &
    Omit<HTMLAttributes<HTMLDivElement>, keyof XYPadThumbProps>

  let {
    color,
    children,
    style,
    'aria-label': ariaLabel,
    'aria-labelledby': ariaLabelledby,
    'aria-describedby': ariaDescribedby,
    'aria-valuetext': ariaValuetext,
    ...rest
  }: Props = $props()

  const pad = useXYPadContext()
  checkPlacement('XYPad.Thumb', 'XYPad.Area')

  // Per axis, since the thumb holds one input for each.
  const labels = $derived(toXY(ariaLabel))
  const labelledby = $derived(toXY(ariaLabelledby))
  const describedby = $derived(toXY(ariaDescribedby))
  const valueText = $derived(toXY(ariaValuetext))

  let x: HTMLInputElement | null = $state(null)
  let y: HTMLInputElement | null = $state(null)

  // Root focuses the thumb when a drag starts, wherever it was placed.
  $effect(() => {
    pad.setThumb(x)
    return () => pad.setThumb(null)
  })

  function onInput(axis: 0 | 1, target: HTMLInputElement) {
    if (pad.readonly) {
      target.value = String(pad.value[axis])
      return
    }
    const next = [...pad.value] as [number, number]
    next[axis] = target.valueAsNumber
    pad.change(next)
  }

  /** Move the focus to the x input. */
  export function focus() {
    if (!pad.disabled) x?.focus()
  }

  /** Take the focus away from both inputs. */
  export function blur() {
    x?.blur()
    y?.blur()
  }
</script>

<div
  data-disabled={pad.disabled ? '' : undefined}
  data-readonly={pad.readonly ? '' : undefined}
  {...rest}
  style="position: absolute; translate: var(--translate, -50% -50%); z-index: 100; {style ??
    ''}"
  style:--color={color}
  style:left="{pad.percent[0]}%"
  style:top="{pad.percent[1]}%"
>
  <VisuallyHiddenRangeInput
    bind:ref={x}
    data-axis="x"
    value={pad.value[0]}
    min={pad.min[0]}
    max={pad.max[0]}
    step={pad.step[0]}
    disabled={pad.disabled}
    aria-readonly={pad.readonly}
    aria-orientation="horizontal"
    aria-label={labels[0] ?? 'x'}
    aria-labelledby={labelledby[0]}
    aria-describedby={describedby[0]}
    aria-valuetext={valueText[0]}
    oninput={(event) => onInput(0, event.currentTarget)}
  />
  <VisuallyHiddenRangeInput
    bind:ref={y}
    data-axis="y"
    value={pad.value[1]}
    min={pad.min[1]}
    max={pad.max[1]}
    step={pad.step[1]}
    disabled={pad.disabled}
    aria-readonly={pad.readonly}
    aria-orientation="vertical"
    aria-label={labels[1] ?? 'y'}
    aria-labelledby={labelledby[1]}
    aria-describedby={describedby[1]}
    aria-valuetext={valueText[1]}
    oninput={(event) => onInput(1, event.currentTarget)}
  />
  {@render children?.()}
</div>
