// packages/svelte/src/components/XYPad/Area.svelte
<script lang="ts">
  import { setPlacement } from '../_util/placement.js'

  import { useXYPadContext } from './context.js'

  import type { Snippet } from 'svelte'
  import type { HTMLAttributes } from 'svelte/elements'

  type Props = HTMLAttributes<HTMLDivElement> & {
    ref?: HTMLDivElement | null
    children?: Snippet
  }

  let { ref = $bindable(null), children, style, ...rest }: Props = $props()

  const pad = useXYPadContext()
  setPlacement('XYPad.Area')

  // The area is what the pointer position is normalized against.
  $effect(() => {
    pad.setArea(ref)
    return () => pad.setArea(null)
  })
</script>

<!-- The thumb inside is placed against this box. -->
<div bind:this={ref} style="position: relative; {style ?? ''}" {...rest}>
  {@render children?.()}
</div>

// packages/react/src/components/XYPad/Area.tsx
import { ComponentPropsWithoutRef, CSSProperties, forwardRef } from 'react'

import { useComposedRefs } from '../../compose-refs'
import { cssLength } from '../_util/css-length'
import { Placement } from '../_util/Placement'

import { useXYPadContext } from './context'

export interface XYPadAreaProps {
  /** Sets `--width`; the size the theme gives it stands when omitted. */
  width?: number | string
  /** Sets `--height`; the size the theme gives it stands when omitted. */
  height?: number | string
  /** Sets `--color`, for the theme to colour the area with. */
  color?: string
}

type Props = XYPadAreaProps &
  Omit<ComponentPropsWithoutRef<'div'>, keyof XYPadAreaProps>

export const Area = /* @__PURE__ */ forwardRef<HTMLDivElement, Props>(
  function Area(
    { width, height, color, children, className, style, ...props },
    forwardedRef,
  ) {
    const { areaRef } = useXYPadContext()

    // The area is what the pointer position is normalized against, so the
    // context ref is composed with any ref the caller passed.
    const composedRef = useComposedRefs<HTMLDivElement>(forwardedRef, areaRef)

    return (
      <div
        ref={composedRef}
        className={className}
        style={
          {
            '--color': color,
            '--width': cssLength(width),
            '--height': cssLength(height),
            // The thumb inside is placed against this box.
            position: 'relative',
            ...style,
          } as CSSProperties
        }
        {...props}
      >
        <Placement name="XYPad.Area">{children}</Placement>
      </div>
    )
  },
)
