// packages/svelte/src/components/Slider/Marks.svelte
<script lang="ts">
  import { cssLength, sliderMarks } from '@tremolo-ui/dom'

  import { setPlacement } from '../_util/placement.js'

  import { useSliderContext } from './context.js'
  import MarksOption from './MarksOption.svelte'
  import type { SliderMarksProps } from './types.js'

  import type { HTMLAttributes } from 'svelte/elements'

  type Props = SliderMarksProps &
    Omit<HTMLAttributes<HTMLDivElement>, keyof SliderMarksProps>

  let { gap, options, children, style, ...rest }: Props = $props()

  const slider = useSliderContext()
  setPlacement('Slider.Marks')

  const marks = $derived.by(() => {
    if (!options) return []
    const list = sliderMarks(options, slider.min, slider.max, slider.step)
    // In the order they are on screen.
    return slider.vertical !== slider.reverse ? list.reverse() : list
  })
</script>

<!-- Each option inside is placed against this box. -->
<div
  data-orientation={slider.vertical ? 'vertical' : 'horizontal'}
  style="position: relative; {style ?? ''}"
  style:--gap={cssLength(gap)}
  {...rest}
>
  {#if options}
    {#each marks as { value, mark, label } (value)}
      <MarksOption {value} {mark} label={label ? undefined : null} />
    {/each}
  {:else}
    {@render children?.()}
  {/if}
</div>

// packages/react/src/components/Slider/Marks.tsx
import { ComponentPropsWithoutRef, CSSProperties, ReactNode } from 'react'

import { xor } from '@tremolo-ui/functions'

import { cssLength } from '../_util/css-length'
import { Placement } from '../_util/Placement'

import { useSliderContext } from './context'
import { MarksOption } from './MarksOption'
import { generateOptionsList, MarksOptions } from './type'

export interface MarksProps {
  /**
   * Space between the marks and the track. Sets `--gap`; the theme's own
   * spacing stands when this is omitted.
   */
  gap?: number | string
  options?: MarksOptions
  children?: ReactNode
}

export function Marks({
  gap,
  options,
  children,
  className,
  style,
  ...props
}: MarksProps & Omit<ComponentPropsWithoutRef<'div'>, keyof MarksProps>) {
  const min = useSliderContext((s) => s.min)
  const max = useSliderContext((s) => s.max)
  const step = useSliderContext((s) => s.step)
  const vertical = useSliderContext((s) => s.vertical)
  const reverse = useSliderContext((s) => s.reverse)

  const optionsList = options
    ? generateOptionsList(options, min, max, step)
    : []
  if (xor(vertical, reverse)) optionsList.reverse()

  return (
    <div
      className={className}
      data-orientation={vertical ? 'vertical' : 'horizontal'}
      style={
        {
          '--gap': cssLength(gap),
          // Each option inside is placed against this box.
          position: 'relative',
          ...style,
        } as CSSProperties
      }
      {...props}
    >
      <Placement name="Slider.Marks">
        {options
          ? optionsList.map(({ value, mark, label }, index) => {
              return (
                <MarksOption
                  key={index}
                  value={value}
                  mark={mark}
                  label={label ? undefined : null}
                />
              )
            })
          : children}
      </Placement>
    </div>
  )
}
