// packages/svelte/src/components/Slider/Thumb.svelte
<script lang="ts">
  import { checkPlacement } from '../_util/placement.js'
  import VisuallyHiddenRangeInput from '../_util/VisuallyHiddenRangeInput.svelte'

  import { useSliderContext } from './context.js'
  import type { SliderThumbProps } from './types.js'

  import type { HTMLAttributes } from 'svelte/elements'

  type Props = SliderThumbProps &
    Omit<HTMLAttributes<HTMLDivElement>, keyof SliderThumbProps>

  let {
    color,
    children,
    style,
    // Pulled out so that they land on the range input: the input is the
    // control and takes the focus, and a name on a plain div is ignored.
    'aria-label': ariaLabel,
    'aria-labelledby': ariaLabelledby,
    'aria-describedby': ariaDescribedby,
    'aria-valuetext': ariaValuetext,
    ...rest
  }: Props = $props()

  const slider = useSliderContext()
  checkPlacement('Slider.Thumb', 'Slider.Track')

  let input: HTMLInputElement | null = $state(null)

  // Root focuses the thumb when a drag starts, wherever it was placed.
  $effect(() => {
    slider.setThumb(input)
    return () => slider.setThumb(null)
  })

  /** Move the focus to the thumb's input. */
  export function focus() {
    if (!slider.disabled) input?.focus()
  }

  /** Take the focus away from the thumb's input. */
  export function blur() {
    input?.blur()
  }
</script>

<!-- Placed by a percentage of the track, measured from its own centre;
  `--translate` is there for a thumb that should hang off its edge. Where it
  sits is the component's decision, so it comes after the caller's style. -->
<div
  data-disabled={slider.disabled ? '' : undefined}
  data-readonly={slider.readonly ? '' : undefined}
  {...rest}
  style="position: absolute; translate: var(--translate, -50% -50%); z-index: 100; {style ??
    ''}"
  style:--color={color}
  style:top={slider.orientation === 'vertical' ? `${slider.percent}%` : '50%'}
  style:left={slider.orientation === 'vertical' ? '50%' : `${slider.percent}%`}
>
  <VisuallyHiddenRangeInput
    bind:ref={input}
    value={slider.value}
    min={slider.min}
    max={slider.max}
    step={slider.step}
    disabled={slider.disabled}
    aria-readonly={slider.readonly}
    aria-orientation={slider.orientation}
    aria-label={ariaLabel}
    aria-labelledby={ariaLabelledby}
    aria-describedby={ariaDescribedby}
    aria-valuetext={ariaValuetext}
    oninput={(event) => {
      const target = event.currentTarget
      if (slider.readonly) {
        target.value = String(slider.value)
        return
      }
      slider.change(target.valueAsNumber)
    }}
  />
  {@render children?.()}
</div>

// packages/react/src/components/Slider/Thumb.tsx
import {
  ComponentPropsWithoutRef,
  CSSProperties,
  forwardRef,
  Ref,
  useImperativeHandle,
  useRef,
} from 'react'

import { useCheckPlacement } from '../_util/Placement'
import { VisuallyHiddenRangeInput } from '../_util/VisuallyHiddenRangeInput'

import { useSliderContext } from './context'

import type { CSSVariables } from '../../css-variables'

export interface SliderThumbProps {
  /**
   * Sets `--color`, for the theme to colour the thumb with. The size is not
   * set here but by `--thumb-size` on `Slider.Root`, so that the root can
   * leave the matching room around the track.
   */
  color?: string

  style?: CSSProperties & CSSVariables<'color' | 'translate'>

  /**
   * Receives `focus` and `blur` for the range input inside, which do nothing
   * while the slider is disabled. `ref` reaches the thumb element itself.
   */
  actionsRef?: Ref<SliderThumbMethods>
}

export interface SliderThumbMethods {
  focus: () => void
  blur: () => void
}

type Props = SliderThumbProps &
  Omit<ComponentPropsWithoutRef<'div'>, keyof SliderThumbProps>

export const Thumb = /* @__PURE__ */ forwardRef<HTMLDivElement, Props>(
  function Thumb(
    {
      color,
      children,
      className,
      style,
      // Pulled out of `props` so that they land on the range input rather than
      // on the thumb: the input is the control, it takes the focus, and a name
      // on a plain div would be ignored. No declaration in `SliderThumbProps`
      // is needed for this — they are already on the div attributes it is
      // merged with, with the same types.
      'aria-label': ariaLabel,
      'aria-labelledby': ariaLabelledby,
      'aria-describedby': ariaDescribedby,
      'aria-valuetext': ariaValuetext,
      actionsRef,
      ...props
    },
    forwardedRef,
  ) {
    const inputRef = useRef<HTMLInputElement>(null)
    const {
      value,
      min,
      max,
      step,
      orientation,
      disabled,
      readOnly,
      onChange,
      percent,
      thumbRef,
    } = useSliderContext()

    // The thumb is positioned against the track.
    useCheckPlacement('Slider.Thumb', 'Slider.Track')

    const methods = () => ({
      focus() {
        if (!disabled) inputRef.current?.focus()
      },
      blur() {
        inputRef.current?.blur()
      },
    })

    useImperativeHandle(actionsRef, methods, [disabled])
    // Root focuses the thumb when a drag starts, wherever the user placed it.
    useImperativeHandle(thumbRef, methods, [disabled])

    return (
      <div
        ref={forwardedRef}
        className={className}
        data-disabled={disabled ? '' : undefined}
        data-readonly={readOnly ? '' : undefined}
        {...props}
        style={{
          ...{ '--color': color },
          // Not a style but the mechanics of the position below: the thumb is
          // placed by a percentage of the track, which needs it out of flow
          // and measured from its own centre. `--translate` is there for a
          // thumb that should hang off its edge instead.
          position: 'absolute',
          translate: 'var(--translate, -50% -50%)',
          zIndex: 100,
          ...style,
          // Where the thumb sits is the component's decision, not a style: a
          // `left` from the caller would take it off the track, so it is
          // written after theirs.
          top: orientation === 'vertical' ? `${percent}%` : '50%',
          left: orientation === 'vertical' ? '50%' : `${percent}%`,
        }}
      >
        <VisuallyHiddenRangeInput
          ref={inputRef}
          value={value}
          min={min}
          max={max}
          step={step}
          disabled={disabled}
          aria-readonly={readOnly}
          aria-orientation={orientation}
          aria-label={ariaLabel}
          aria-labelledby={ariaLabelledby}
          aria-describedby={ariaDescribedby}
          aria-valuetext={ariaValuetext}
          onChange={(event) => {
            if (readOnly) {
              event.currentTarget.value = String(value)
              return
            }
            onChange?.(event.currentTarget.valueAsNumber)
          }}
        />
        {children}
      </div>
    )
  },
)
