// packages/react/src/components/NumberInput/InputField.tsx
import {
  ComponentPropsWithoutRef,
  forwardRef,
  useEffect,
  useLayoutEffect,
  useRef,
  useState,
} from 'react'

import {
  caretAtDecimalOffset,
  caretDecimalOffset,
  numberSpan,
} from '@tremolo-ui/dom/internal'

import { useComposedRefs } from '../../compose-refs'

import { useNumberInputContext, useNumberInputGesture } from './context'

// The value belongs to `NumberInput.Root`, and the field is always text.
type Props = Omit<
  ComponentPropsWithoutRef<'input'>,
  'type' | 'value' | 'defaultValue'
>

/**
 * The text field of a `NumberInput`, and the only place the value can be typed.
 *
 * While the user types, their own text stands rather than `format(value)`, so
 * that a half-finished entry is not rewritten under the caret.
 *
 * How it behaves on focus, Enter and the arrow keys is set on `Root`
 * (`selectOnFocus`, `unformatOnFocus`, `keepCaretOnStep`, `blurOnEnter`).
 */
export const InputField = /* @__PURE__ */ forwardRef<HTMLInputElement, Props>(
  function InputField(
    { className, style, onChange, onFocus, onBlur, onKeyDown, ...props },
    forwardedRef,
  ) {
    const {
      value,
      min,
      max,
      step,
      disabled,
      readOnly,
      keyboard,
      selectOnFocus,
      unformatOnFocus,
      keepCaretOnStep,
      blurOnEnter,
      text,
      editing,
      outOfRange,
      setDraft,
      commitDraft,
      nudge,
      inputRef,
    } = useNumberInputContext()

    const gesture = useNumberInputGesture()
    const [focused, setFocused] = useState(false)

    // Only until the first keystroke: from then on the draft is the user's own
    // text and stands on its own, formatted or not.
    const shown = unformatOnFocus && focused && !editing ? String(value) : text

    // Selecting has to wait for that swap. Called from the focus handler it
    // would run against the formatted text still in the input and cover the
    // wrong characters.
    useEffect(() => {
      if (!focused || selectOnFocus === 'none') return
      const input = inputRef.current
      if (!input) return
      if (selectOnFocus === 'all') {
        input.setSelectionRange(0, input.value.length)
      } else {
        const span = numberSpan(input.value)
        if (span) input.setSelectionRange(span.start, span.end)
      }
      // Deliberately not re-run as the text changes: that would drag the
      // selection back over what the user is typing.
    }, [focused, selectOnFocus, inputRef])

    /**
     * Where to put the caret once the stepped value has been rendered, and the
     * text it was measured against.
     */
    const caretAfterStep = useRef<{ offset: number; from: string } | null>(null)

    // A layout effect rather than a plain one: the caret is moved before the
    // browser paints, so it is never seen at the end of the text first.
    useLayoutEffect(() => {
      const pending = caretAfterStep.current
      if (!pending) return
      caretAfterStep.current = null

      const input = inputRef.current
      // The step may have been clamped away, leaving the text as it was. The
      // caret has not moved either, since the key press was prevented.
      if (!input || input.value === pending.from) return

      const caret = caretAtDecimalOffset(input.value, pending.offset)
      input.setSelectionRange(caret, caret)
    })

    const composedRef = useComposedRefs<HTMLInputElement>(
      forwardedRef,
      inputRef,
    )

    return (
      <input
        ref={composedRef}
        className={className}
        // Not type="number": that brings native spinners and a value the browser
        // parses itself, neither of which survives a unit suffix.
        type="text"
        inputMode="decimal"
        role="spinbutton"
        value={shown}
        disabled={disabled}
        readOnly={readOnly}
        aria-disabled={disabled}
        aria-readonly={readOnly}
        data-disabled={disabled ? '' : undefined}
        data-readonly={readOnly ? '' : undefined}
        aria-valuenow={value}
        aria-valuemin={min}
        aria-valuemax={max}
        // The formatted text, even while the field shows the plain number: it is
        // the one that says what the value means.
        aria-valuetext={text}
        step={step}
        data-out-of-range={outOfRange ? '' : undefined}
        style={style}
        onChange={(event) => {
          // The text is the user's own now, so a caret measured against the
          // stepped one no longer means anything.
          caretAfterStep.current = null
          setDraft(event.currentTarget.value)
          onChange?.(event)
        }}
        onFocus={(event) => {
          setFocused(true)
          onFocus?.(event)
        }}
        onBlur={(event) => {
          setFocused(false)
          // Nothing was typed, so there is no draft and this returns at once —
          // taking focus and leaving again never commits anything.
          commitDraft()
          onBlur?.(event)
        }}
        onKeyDown={(event) => {
          const key = event.key
          if (key === 'Enter') {
            commitDraft()
            if (blurOnEnter) event.currentTarget.blur()
          } else if (
            keyboard &&
            !disabled &&
            !readOnly &&
            (key === 'ArrowUp' || key === 'ArrowDown') &&
            // Arrow keys pick a candidate while an IME is converting. Stepping
            // the value there would fight the conversion, and moving the caret
            // would break it outright.
            !event.nativeEvent.isComposing
          ) {
            event.preventDefault()
            const input = event.currentTarget
            if (keepCaretOnStep && input.selectionStart !== null) {
              caretAfterStep.current = {
                offset: caretDecimalOffset(input.value, input.selectionStart),
                from: input.value,
              }
            }
            gesture?.key()
            nudge(key === 'ArrowUp' ? 1 : -1, keyboard, event)
          }
          onKeyDown?.(event)
        }}
        {...props}
      />
    )
  },
)

// packages/svelte/src/components/NumberInput/InputField.svelte
<script lang="ts">
  import {
    caretAtDecimalOffset,
    caretDecimalOffset,
    numberSpan,
  } from '@tremolo-ui/dom/internal'
  import { tick } from 'svelte'

  import { useNumberInputContext, useNumberInputGesture } from './context.js'

  import type { HTMLInputAttributes } from 'svelte/elements'

  // The value belongs to `NumberInput.Root`, and the field is always text.
  type Props = Omit<HTMLInputAttributes, 'type' | 'value'> & {
    ref?: HTMLInputElement | null
  }

  let {
    ref = $bindable(null),
    onfocus,
    oninput,
    onblur,
    onkeydown,
    ...rest
  }: Props = $props()

  const field = useNumberInputContext()
  const gesture = useNumberInputGesture()

  $effect(() => {
    field.setInput(ref)
    return () => field.setInput(null)
  })

  let focused = $state(false)

  // Only until the first keystroke: from then on the draft is the user's own
  // text and stands on its own, formatted or not.
  const shown = $derived(
    field.unformatOnFocus && focused && !field.editing
      ? String(field.value)
      : field.text,
  )

  async function select() {
    if (field.selectOnFocus === 'none') return
    // Selecting has to wait for `unformatOnFocus` to swap the text in, or it
    // would cover the wrong characters.
    await tick()
    const input = ref
    if (!input || !focused) return
    const span =
      field.selectOnFocus === 'all'
        ? { start: 0, end: input.value.length }
        : numberSpan(input.value)
    if (span) input.setSelectionRange(span.start, span.end)
  }

  async function step(direction: number, event: KeyboardEvent) {
    const input = event.currentTarget as HTMLInputElement
    const from = input.value
    const offset =
      field.keepCaretOnStep && input.selectionStart !== null
        ? caretDecimalOffset(from, input.selectionStart)
        : null
    gesture?.key()
    field.nudge(direction, field.keyboard!, event)
    if (offset === null) return
    await tick()
    // The step may have been clamped away, leaving the text as it was.
    if (input.value === from) return
    const caret = caretAtDecimalOffset(input.value, offset)
    input.setSelectionRange(caret, caret)
  }
</script>

<!-- Not type="number": that brings native spinners and a value the browser
  parses itself, neither of which survives a unit suffix. The ARIA value text
  is the formatted text even while the plain number is shown: it is the one
  that says what the value means. -->
<!-- The caller's attributes go first, so that the field's own state —
  disabled, readonly, the ARIA — cannot be overridden by them. -->
<input
  {...rest}
  bind:this={ref}
  type="text"
  inputmode="decimal"
  role="spinbutton"
  value={shown}
  disabled={field.disabled}
  readonly={field.readonly}
  aria-disabled={field.disabled}
  aria-readonly={field.readonly}
  aria-valuenow={field.value}
  aria-valuemin={field.min}
  aria-valuemax={field.max}
  aria-valuetext={field.text}
  step={field.step}
  data-disabled={field.disabled ? '' : undefined}
  data-readonly={field.readonly ? '' : undefined}
  data-out-of-range={field.outOfRange ? '' : undefined}
  oninput={(event) => {
    field.setDraft(event.currentTarget.value)
    oninput?.(event)
  }}
  onfocus={(event) => {
    focused = true
    select()
    onfocus?.(event)
  }}
  onblur={(event) => {
    focused = false
    // Nothing was typed, so there is no draft and this returns at once —
    // taking focus and leaving again never commits anything.
    field.commitDraft()
    onblur?.(event)
  }}
  onkeydown={(event) => {
    const key = event.key
    if (key === 'Enter') {
      field.commitDraft()
      if (field.blurOnEnter) event.currentTarget.blur()
    } else if (
      field.keyboard &&
      !field.disabled &&
      !field.readonly &&
      (key === 'ArrowUp' || key === 'ArrowDown') &&
      // Arrow keys pick a candidate while an IME is converting.
      !event.isComposing
    ) {
      event.preventDefault()
      step(key === 'ArrowUp' ? 1 : -1, event)
    }
    onkeydown?.(event)
  }}
/>
