// packages/react/src/components/NumberInput/StepperButton.tsx
import { ComponentPropsWithoutRef, ReactNode, CSSProperties } from 'react'

import { useLongPress } from '../../hooks/useLongPress'

import { useNumberInputContext, useStepperContext } from './context'

import type { CSSVariables } from '../../css-variables'

/**
 * `--stepper-icon-size` is read by the default arrow inside, and set on the
 * button so that it inherits there.
 */
export type StepperButtonProps = Omit<
  ComponentPropsWithoutRef<'div'>,
  'style'
> & {
  style?: CSSProperties & CSSVariables<'stepper-icon-size'>
}

type Props = StepperButtonProps

/**
 * Shared body of `IncrementStepper` and `DecrementStepper`: the two differ only
 * in which way they move the value and which arrow they draw.
 */
export function StepperButton({
  direction,
  variant,
  icon,
  className,
  style,
  children,
  onPointerDown,
  ...props
}: Props & {
  direction: 1 | -1
  variant: 'increment' | 'decrement'
  icon: ReactNode
}) {
  const { step, disabled, readonly, atMin, atMax, nudge } =
    useNumberInputContext()
  const stepper = useStepperContext()

  // Not memoized: `useLongPress` only ever calls it through a ref, so a fresh
  // identity per render costs nothing.
  const press = useLongPress(() => {
    // Once the pointer has actually travelled, the drag on `Stepper` owns the
    // value; repeating on top of it would move it twice.
    if (stepper?.moved()) return
    nudge(direction, ['raw', step])
  })

  return (
    <div
      className={className}
      role="button"
      tabIndex={-1}
      // A bare arrow has no accessible name of its own. Overridable, since a
      // caller may need it in their own language.
      aria-label={direction > 0 ? 'Increment' : 'Decrement'}
      aria-disabled={disabled || (direction > 0 ? atMax : atMin)}
      // `role="button"` does not take aria-readonly, so the state reaches the
      // styles through the data attribute alone.
      data-disabled={
        disabled || (direction > 0 ? atMax : atMin) ? '' : undefined
      }
      data-readonly={readonly ? '' : undefined}
      style={style}
      onPointerDown={(event) => {
        if (!disabled && !readonly) press(event)
        onPointerDown?.(event)
      }}
      {...props}
    >
      {children ?? icon}
    </div>
  )
}

export function StepperArrow({ up }: { up: boolean }) {
  return (
    <svg
      // The arrow the component draws when no children are given, so it sizes
      // itself rather than asking a stylesheet to.
      style={{
        width: 'var(--stepper-icon-size)',
        height: 'var(--stepper-icon-size)',
      }}
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polyline points={up ? '18 15 12 9 6 15' : '6 9 12 15 18 9'} />
    </svg>
  )
}

// packages/svelte/src/components/NumberInput/StepperButton.svelte
<script lang="ts">
  import { longPress } from '../../actions/long-press.js'

  import { useNumberInputContext, useStepperContext } from './context.js'

  import type { Snippet } from 'svelte'
  import type { HTMLAttributes } from 'svelte/elements'

  type Props = HTMLAttributes<HTMLDivElement> & {
    direction: 1 | -1
    children?: Snippet
  }

  let { direction, children, ...rest }: Props = $props()

  const field = useNumberInputContext()
  const stepper = useStepperContext()

  const blocked = $derived(
    field.disabled || (direction > 0 ? field.atMax : field.atMin),
  )

  const pressOptions = {
    onPress: () => {
      if (field.disabled || field.readonly) return
      // Once the pointer has actually travelled, the drag on `Stepper` owns
      // the value; repeating on top of it would move it twice.
      if (stepper?.moved()) return
      field.nudge(direction, ['raw', field.step])
    },
  }
</script>

<!-- A bare arrow has no accessible name of its own. Overridable, since a
  caller may need it in their own language. `role="button"` does not take
  aria-readonly, so that state reaches the styles through the data attribute
  alone. -->
<div
  role="button"
  tabindex="-1"
  aria-label={direction > 0 ? 'Increment' : 'Decrement'}
  aria-disabled={blocked}
  data-disabled={blocked ? '' : undefined}
  data-readonly={field.readonly ? '' : undefined}
  use:longPress={pressOptions}
  {...rest}
>
  {#if children}
    {@render children()}
  {:else}
    <svg
      style="width: var(--stepper-icon-size); height: var(--stepper-icon-size)"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      stroke-width="2"
      stroke-linecap="round"
      stroke-linejoin="round"
    >
      <polyline points={direction > 0 ? '18 15 12 9 6 15' : '6 9 12 15 18 9'} />
    </svg>
  {/if}
</div>
