// packages/react/src/components/Slider/Track.tsx
import {
  ComponentPropsWithoutRef,
  CSSProperties,
  forwardRef,
  ReactNode,
} from 'react'

import { xor } from '@tremolo-ui/functions'

import { useComposedRefs } from '../../compose-refs'
import { cssLength } from '../_util/css-length'
import { Placement } from '../_util/Placement'

import { useSliderContext } from './context'

export interface SliderTrackProps {
  /**
   * How long the track is along the axis the slider runs. Sets `--length`;
   * the size the theme gives it stands when this is omitted.
   */
  length?: number | string
  /** How thick the track is across that axis. Sets `--thickness`. */
  thickness?: number | string

  /** Colour of the part from `min` to the value. Sets `--active`. */
  active?: string
  /** Colour of the rest of the track. Sets `--inactive`. */
  inactive?: string

  className?: string
  style?: CSSProperties
  /** `<Slider.Thumb />` goes here. */
  children?: ReactNode
}

type Props = SliderTrackProps &
  Omit<ComponentPropsWithoutRef<'div'>, keyof SliderTrackProps>

export const Track = /* @__PURE__ */ forwardRef<HTMLDivElement, Props>(
  function Track(
    {
      length,
      thickness,
      active,
      inactive,
      children,
      className,
      style,
      ...props
    },
    forwardedRef,
  ) {
    const { vertical, reverse, disabled, percent, trackRef } =
      useSliderContext()

    // The track is what the pointer position is normalized against, so the
    // context ref is composed with any ref the caller passed.
    const composedRef = useComposedRefs<HTMLDivElement>(forwardedRef, trackRef)

    return (
      <div
        ref={composedRef}
        className={className}
        data-disabled={disabled ? '' : undefined}
        data-orientation={vertical ? 'vertical' : 'horizontal'}
        // Which end the value grows from. `percent` is already the position on
        // screen, so this only says which side of it is the filled one.
        data-flipped={xor(vertical, reverse) ? '' : undefined}
        style={
          {
            '--active': active,
            '--inactive': inactive,
            '--length': cssLength(length),
            '--thickness': cssLength(thickness),
            // Where the value sits, for the theme to paint the fill with. The
            // component draws nothing itself: this is the one number CSS cannot
            // work out on its own.
            '--percent': `${percent}%`,
            // The thumb inside is placed against this box.
            position: 'relative',
            ...style,
          } as CSSProperties
        }
        {...props}
      >
        <Placement name="Slider.Track">{children}</Placement>
      </div>
    )
  },
)

// packages/svelte/src/components/Slider/Track.svelte
<script lang="ts">
  import { cssLength } from '@tremolo-ui/dom'

  import { setPlacement } from '../_util/placement.js'

  import { useSliderContext } from './context.js'
  import type { SliderTrackProps } from './types.js'

  import type { HTMLAttributes } from 'svelte/elements'

  type Props = SliderTrackProps &
    Omit<HTMLAttributes<HTMLDivElement>, keyof SliderTrackProps>

  let {
    length,
    thickness,
    active,
    inactive,
    ref = $bindable(null),
    children,
    style,
    ...rest
  }: Props = $props()

  const slider = useSliderContext()
  setPlacement('Slider.Track')

  // The track is what the pointer position is normalized against.
  $effect(() => {
    slider.setTrack(ref)
    return () => slider.setTrack(null)
  })
</script>

<!-- `--percent` is where the value sits, for the theme to paint the fill
  with: the one number CSS cannot work out on its own. -->
<div
  bind:this={ref}
  data-disabled={slider.disabled ? '' : undefined}
  data-orientation={slider.vertical ? 'vertical' : 'horizontal'}
  data-flipped={slider.vertical !== slider.reverse ? '' : undefined}
  style="position: relative; {style ?? ''}"
  style:--active={active}
  style:--inactive={inactive}
  style:--length={cssLength(length)}
  style:--thickness={cssLength(thickness)}
  style:--percent="{slider.percent}%"
  {...rest}
>
  {@render children?.()}
</div>
