// packages/svelte/src/components/PointsEditor/SelectionBox.svelte
<script lang="ts">
  import { checkPlacement } from '../_util/placement.js'

  import { usePointsEditorContext } from './context.js'

  import type { Snippet } from 'svelte'
  import type { HTMLAttributes } from 'svelte/elements'

  type Props = HTMLAttributes<HTMLDivElement> & { children?: Snippet }

  let { children, style, ...rest }: Props = $props()

  const points = usePointsEditorContext()
  checkPlacement('PointsEditor.SelectionBox', 'PointsEditor.Container')
</script>

<!-- Drawn over the points while a drag runs, and taking none of the pointer:
  the drag underneath is what it is reporting on. Nothing is rendered while no
  drag is running. -->
{#if points.selectionBox}
  {@const box = points.selectionBox}
  <div
    {...rest}
    style="position: absolute; z-index: 20; pointer-events: none; {style ?? ''}"
    style:left="{box.x * 100}%"
    style:top="{box.y * 100}%"
    style:width="{box.width * 100}%"
    style:height="{box.height * 100}%"
  >
    {@render children?.()}
  </div>
{/if}

// packages/react/src/components/PointsEditor/SelectionBox.tsx
import { ComponentPropsWithoutRef, CSSProperties } from 'react'

import { useCheckPlacement } from '../_util/Placement'

import { usePointsEditorContext } from './context'

/**
 * The box a drag on empty space draws, and what it covers is selected.
 *
 * Nothing is rendered while no drag is running, and leaving it out leaves the
 * editor without one — the selection still works, it just cannot be seen.
 */
export function SelectionBox({
  children,
  className,
  style,
  ...props
}: ComponentPropsWithoutRef<'div'>) {
  useCheckPlacement('PointsEditor.SelectionBox', 'PointsEditor.Container')

  const selectionBox = usePointsEditorContext((s) => s.selectionBox)
  if (!selectionBox) return null

  return (
    <div
      className={className}
      {...props}
      style={
        {
          // Drawn over the points while a drag runs, and taking none of the
          // pointer: the drag underneath is what it is reporting on.
          position: 'absolute',
          zIndex: 20,
          pointerEvents: 'none',
          ...style,
          // Where the box is and how big it is: the drag, not a style, so it
          // is written after whatever the caller passed.
          left: `${selectionBox.x * 100}%`,
          top: `${selectionBox.y * 100}%`,
          width: `${selectionBox.width * 100}%`,
          height: `${selectionBox.height * 100}%`,
        } as CSSProperties
      }
    >
      {children}
    </div>
  )
}
